### ISSUE TITLE
extract HMAC to its own middleware

### ISSUE THREAD

**Issue by JamesClonk** [jamesclonk-io/stdlib#8]
- [ ] extract from backend-server
- [ ] extract from backend-client
- [ ] make its use an option for backend-client
- [ ] make its use (for all routes) an option during NewBackend creation
- [ ] make it usable as middleware just for some routes (what you'll use it for in the moviedb-backend!)

**Comment by JamesClonk** [comment]
to much hassle, you'll never use it like that anyway..
